### PR TITLE
Adding CacheItemPoolInterface to Service constructors

### PR DESCRIPTION
**Pull request by votemike**

### CODE REVIEW

**Comment by Jayflux** [comment]
🎈 Happy First PR :champagne:

**Comment by BjornTwachtmann** [comment]
Looks good to me :)

A few points that aren't strictly related to this code but I'm going to stick on here anyway because I'm an akward bastard...
a) We should make this a major version bump as it's a breaking change
b) We really need to start refering to this library by version in faucet/clifton/frontend. I think they're still pointing at dev-master.

**Comment by BPScott** [comment]
@BjornTwachtmann: Agreed on A. I'm less convinced by B as that'll result in a lot of version number churn. The fatigue/overhead of having to do version bumps was annoying when dealing with translations, I'm a little wary of reintroducing that here.

**Comment by BjornTwachtmann** [comment]
We can discuss it tomorrow I guess, feel free to merge for now anyway.

**Pull request merged**
