### PR TITLE
Add a utility methods to get valid values from enums

### PR DESCRIPTION
**Pull request by BPScott**
This saves us having to define the list of valid values in multiple
places

### CODE REVIEW

**Comment by votemike** [comment]
These all are used within in_array. Would it be better to pass the value in to the method and let the ENUM do the in_array check?

**Comment by votemike** [comment]
Should all the ENUM extend or implement something with the method `validValues`?

**Comment by BPScott** [comment]
> These all are used within in_array. Would it be better to pass the value in to the method and let the ENUM do the in_array check?

@votemike We'd still need to build the list of valid values that the enum has for the exception message.

**Comment by BjornTwachtmann** [comment]
Seems reasonable. 

Some of the faucet stuff uses some reflection dark magic around enums to enable you to do things like have them check their list of constants for valid values without having to list them, instantiate just using the constant name, etc. I'm not entirely sold on using reflection in user facing code though, this seems less problematic.

**Comment by votemike** [comment]
I didn't mean for you to replace `validValues()` but to go one step further and add an extra method to do that check.  
I'm easy either way.

**Comment by Tasiobg** [comment]
I think having a BaseEnum class and extending it would make sense, at least this is what I have done in past projects and works fine. Example useful functions:
- getConstants() 
- getNameByValue()
- getValueByName()
- isValidName()
- isValidValue()

Related question on stackoverflow https://stackoverflow.com/questions/254514/php-and-enumerations

**Pull request merged**
